### ISSUE TITLE
Export to .pdf - filters not applied with spaces in parameter (2.0.7.dev9)

### ISSUE THREAD

**Issue by John-Miller12** [tableau/tabcmd#176]
Hello, 

This is a continuation of an [existing issue](https://github.com/tableau/tabcmd/issues/163), marked as `fixed`

I am running development branch 2.0.7.dev9 in Windows 10 conda environment with the following command:

`python -m tabcmd export OmniFieldReport/Summary?Zone%%20ZVP=22%%20Ralph%%20McFakeName --pdf -f "C:\Users\c17798\Documents\BatchPdfTest\22RalphMcFakeName.pdf" --logging-level=DEBUG`

The filter name is `Zone ZVP` and the value is `22 Ralph McFakeName`.

*Issue:* While the file is created as expected, no filters are applied. The default view is returned.

I have attached the redacted debug output:
[tabcmd_export_debug.txt](https://github.com/tableau/tabcmd/files/9551123/tabcmd_export_debug.txt)

**Comment by jacalata** [comment]
Not sure yet if there is an encoding bug, but the error trace displayed is a bad debug message that is fixed in #175

**Comment by jacalata** [comment]
I checked into this and yes, this is failing when there's a space in the filter parameter.

**Comment by mkosmicki** [comment]
Is there an update on the status of the bug fix?

**Comment by jacalata** [comment]
@mkosmicki There is no update on the bug for spaces, but the general exporting should be fixed in the latest release, which is available at https://github.com/tableau/tabcmd/releases/tag/v2.0.6 or through pip using the command 
pip install tabcmd --pre

Could you clarify if you are still having problems with all exporting, or just with spaces?

**Comment by woodya-coder** [comment]
I'm new to using Tabcmd, but I just downloaded 2.0 and tried exporting with a parameter name with a space and it couldn't find the item.  I don't think it's working.

**Comment by jacalata** [comment]
No - the problem with spaces is still not fixed, sorry!

**Comment by rneilsen** [comment]
Still doesn't appear to be working with spaces in the parameter name for me, on version 2.0.9 (according to `tabcmd --version`). My testing workbook has parameters named `spacelessint` and `spaced int`, and of the following commands:

```
tabcmd export --no-certcheck 'TabcmdExperiment/Dashboard1?spacelessint=4' --png -f /tmp/1.png
tabcmd export --no-certcheck 'TabcmdExperiment/Dashboard1?spaced%20int=13' --png -f /tmp/2.png
```

the first correctly sets the `spacelessint` parameter to 4 for the dashboard, but the second does **not** set `spaced int` to 13. I also tried the second command with a double-percent (`...spaced%%20int=13`) but that didn't work either.

**Comment by mptalaga** [comment]
We are having issues using tabcmd 2.0 to export PDF files.  We have a filter setup to show a list of Vendors, and we either show all details, or a specific vendor.  With the TabCmd from Tableau Server, we were running the following command, and it generates a PDF for Vendor # 212D.

Due to the MFA implementation, we are trying to switch to TabCmd.exe 2.0, and the export is not working as expected.  The Filter by Vendor_ID isn't functioning.  I've tried 2.0.6, 2.07, and 2.0.10, and they all produce the same result.

`tabcmd.exe export "CommissionStatement/Page1?Vendor_ID=212D" --pagelayout portrait --fullpdf -f ".\212D.pdf" --timeout 4600 --no-prompt`

Why doesn't it it function like TabCmd for Tableau Server?  Is there something we need to change in the report to make it work?

`2023-02-16 15:55:29,897 INFO : (ExportCommand export_command.py: 177): Requesting ''CommissionStatement/Page1?Vendor_ID=212D'' from the server...
2023-02-16 15:55:29,897 DEBUG: (ExportCommand export_command.py: 78): ['CommissionStatement/sheets/Page1', 'CommissionStatement']
2023-02-16 15:55:29,900 DEBUG: (ExportCommand datasources_and_workbooks_command.py: 22): Requesting ''CommissionStatement/sheets/Page1'' from the server...
2023-02-16 15:55:30,085 DEBUG: (ExportCommand export_command.py: 166): CommissionStatement/Page1?Vendor_ID=212D
2023-02-16 15:55:30,085 DEBUG: (ExportCommand datasources_and_workbooks_command.py: 65): CommissionStatement/Page1?Vendor_ID=212D
2023-02-16 15:55:30,086 DEBUG: (ExportCommand export_command.py: 122): Args: portrait, letter, 800, 600, None
2023-02-16 15:55:30,087 WARNING: (ExportCommand datasources_and_workbooks_command.py: 117): Height/width arguments not yet implemented in export
2023-02-16 15:55:30,088 DEBUG: (ExportCommand export_command.py: 171): {'resolution': 'high', 'maxAge': 1, 'vf_Vendor_ID': '212D'}
2023-02-16 15:55:32,234 INFO : (ExportCommand datasources_and_workbooks_command.py: 137): Found attachment: .\212D.png
2023-02-16 15:55:32,235 INFO : (ExportCommand datasources_and_workbooks_command.py: 140): Saved  to ''.\212D.png''`

**Comment by michaelharms6010** [comment]
+1 on this issue. Is this real life?

**Comment by jacalata** [comment]
What version are you using?

**Comment by michaelharms6010** [comment]
> What version are you using?

Thanks for the reply. I'm using this release, tagged v2.0.10 with this issue listed as "known":
[Case sensitivity for users](https://github.com/tableau/tabcmd/releases/tag/v2.0.10)

**Comment by jacalata** [comment]
Got it. I just now published v2.0.11 with the fix for this issue included.

**Comment by michaelharms6010** [comment]
> Got it. I just now published v2.0.11 with the fix for this issue included.

Thanks for the release. 🙏 I'm giving it a try now and getting the same result (No filter is applied in the saved pdf, resulting in *very* overcrowded and illegible views)

Do you see anything obvious that I'm missing? 

I'm running this command:
`.\tabcmd export "IA_PartnerPPPReport/PPPSelectorDashboard?PPP%20Group%20Name=Partner%20-%20FirstName%20LastName%20Region%20Portfolio" --fullpdf -f "C:\tabcmd\OUTPUT\03.2023_PPP\Partner - FirstName LastName Region Portfolio\Partner - FirstName LastName Region Portfolio.pdf"`

I get this output from Tabcmd:
```
Requesting ''IA_PartnerPPPReport/PPPSelectorDashboard?PPP%20Group%20Name=Partner%20-%20FirstName%20LastName%20Region%20Portfolio'' from the server...
Found attachment: C:\tabcmd\OUTPUT\03.2023_PPP\Partner - FirstName LastName Region Portfolio\Partner - FirstName LastName Region Portfolio.pdf
Saved  to ''C:\tabcmd\OUTPUT\03.2023_PPP\Partner - FirstName LastName Region Portfolio\Partner - FirstName LastName Region Portfolio.pdf''
```

If I append the request string `IA_PartnerPPPReport/PPPSelectorDashboard?PPP%20Group%20Name=Partner%20-%20FirstName%20LastName%20Region%20Portfolio` to Tableau Online after `/views/` , the filter is applied correctly.

**Comment by jacalata** [comment]
Hm, try starting the filter with Parameters - like "PPPSelectorDashboard?Parameters.PPP%20Group%20Name........"

if you could turn on debug logging as well, that might help: --logging-level=DEBUG

**Comment by michaelharms6010** [comment]
Thanks, I gave this a try. With `Parameters.` added to the query, the saved PDF is unchanged. I get the same unfiltered PDF.

The debug logging outputs this:
```
2023-03-01 14:22:09,734 DEBUG: (tabcmd.execution.tabcmd_controller tabcmd_controller.py: 34): Namespace(certificate=None, continue_if_exists=False, country=None, csv=False, filename='C:\\tabcmd\\OUTPUT\\03.2023_PPP\\Partner - FirstName LastName Region Portfolio\\Partner - FirstName LastName Region Portfolio.pdf', filter=None, fullpdf=True, func=<class 'tabcmd.commands.datasources_and_workbooks.export_command.ExportCommand'>, height=600, language=None, logging_level='DEBUG', no_certcheck=False, no_cookie=False, no_prompt=False, no_proxy=True, pagelayout=None, pagesize='letter', password='REDACTED', password_file=None, pdf=False, png=False, proxy=None, server=None, site_name='', timeout=None, token_file=None, token_name=None, token_value=None, url='IA_PartnerPPPReport/PPPSelectorDashboard?Parameters.PPP%20Group%20Name=Partner%20-%20FirstName%20LastName%20Region%20Portfolio', username=None, width=800)
2023-03-01 14:22:09,735 DEBUG: (ExportCommand export_command.py: 74): ======================= Launching command =======================
2023-03-01 14:22:09,738 INFO : (ExportCommand session.py: 199): Creating new session
2023-03-01 14:22:09,739 INFO : (ExportCommand session.py: 213): =====   Server: https://10ay.online.tableau.com/
2023-03-01 14:22:09,739 INFO : (ExportCommand session.py: 215): =====   Username: [USERNAME_REDACTED]
2023-03-01 14:22:09,740 INFO : (ExportCommand session.py: 219): Tableau Server Site: energyprint
2023-03-01 14:22:09,740 INFO : (ExportCommand session.py: 201): Connecting to the server...
2023-03-01 14:22:09,741 DEBUG: (ExportCommand session.py: 154): Setting up request options
2023-03-01 14:22:09,741 DEBUG: (ExportCommand session.py: 168): {'headers': {'User-Agent': 'Tabcmd/0.1.dev1'}, 'verify': False}
2023-03-01 14:22:09,742 DEBUG: (ExportCommand session.py: 179): Finished setting up connection
2023-03-01 14:22:10,189 DEBUG: (ExportCommand session.py: 238): Signing in...https://10ay.online.tableau.com/
2023-03-01 14:22:10,189 DEBUG: (ExportCommand session.py: 239): NAME: [USERNAME_REDACTED] SITEID: ''energyprint''
2023-03-01 14:22:10,456 INFO : (ExportCommand session.py: 250): Succeeded
2023-03-01 14:22:10,456 DEBUG: (ExportCommand session.py: 253): Signed into https://10ay.online.tableau.com/energyprint as [USERNAME_REDACTED]
2023-03-01 14:22:10,458 INFO : (ExportCommand export_command.py: 173): Requesting ''IA_PartnerPPPReport/PPPSelectorDashboard?Parameters.PPP%20Group%20Name=Partner%20-%20FirstName%20LastName%20Region%20Portfolio'' from the server...
2023-03-01 14:22:10,459 DEBUG: (ExportCommand export_command.py: 78): ['view_url:', 'IA_PartnerPPPReport/sheets/PPPSelectorDashboard', 'workbook:', 'IA_PartnerPPPReport']
2023-03-01 14:22:10,460 DEBUG: (ExportCommand datasources_and_workbooks_command.py: 38): Requesting ''IA_PartnerPPPReport'' from the server...
2023-03-01 14:22:10,460 DEBUG: (ExportCommand datasources_and_workbooks_command.py: 42): {'pageNumber': 1, 'pageSize': 100, 'filter': 'contentUrl:eq:IA_PartnerPPPReport'}
2023-03-01 14:22:10,690 DEBUG: (ExportCommand export_command.py: 131): IA_PartnerPPPReport/PPPSelectorDashboard?Parameters.PPP%20Group%20Name=Partner%20-%20FirstName%20LastName%20Region%20Portfolio
2023-03-01 14:22:10,691 DEBUG: (ExportCommand datasources_and_workbooks_command.py: 66): IA_PartnerPPPReport/PPPSelectorDashboard?Parameters.PPP%20Group%20Name=Partner%20-%20FirstName%20LastName%20Region%20Portfolio
2023-03-01 14:22:10,692 DEBUG: (ExportCommand datasources_and_workbooks_command.py: 70): Query parameters: Parameters.PPP%20Group%20Name=Partner%20-%20FirstName%20LastName%20Region%20Portfolio
2023-03-01 14:22:10,693 DEBUG: (ExportCommand datasources_and_workbooks_command.py: 76): ['Parameters.PPP%20Group%20Name=Partner%20-%20FirstName%20LastName%20Region%20Portfolio']
2023-03-01 14:22:10,694 DEBUG: (ExportCommand datasources_and_workbooks_command.py: 95): url had `PPP%20Group%20Name=Partner%20-%20FirstName%20LastName%20Region%20Portfolio`, saved as `PPP Group Name=Partner - FirstName LastName Region Portfolio`
2023-03-01 14:22:10,694 DEBUG: (ExportCommand datasources_and_workbooks_command.py: 103): handling filter param PPP Group Name=Partner - FirstName LastName Region Portfolio
2023-03-01 14:22:10,695 DEBUG: (ExportCommand export_command.py: 135): {'type': 'letter', 'maxAge': 1, 'vf_PPP Group Name': 'Partner - FirstName LastName Region Portfolio'}
2023-03-01 14:22:11,906 INFO : (ExportCommand datasources_and_workbooks_command.py: 151): Found attachment: C:\tabcmd\OUTPUT\03.2023_PPP\Partner - FirstName LastName Region Portfolio\Partner - FirstName LastName Region Portfolio.pdf
2023-03-01 14:22:11,907 INFO : (ExportCommand datasources_and_workbooks_command.py: 154): Saved  to ''C:\tabcmd\OUTPUT\03.2023_PPP\Partner - FirstName LastName Region Portfolio\Partner - FirstName LastName Region Portfolio.pdf''
```

**Comment by jacalata** [comment]
In my testing the filters do not work if you export a full workbook. They should work if you export a single view.  I will list this as a new known issue - sorry for the hassle! 

FYI, there is also an easier syntax you can use now (for views, at least)
Existing syntax: 
tabcmd export /WorldIndicators/Population?Birth%20Rate%20Bin=1.5-3%25 --pdf
New syntax, with no need to encode the parameter values:
tabcmd export /WorldIndicators/Population --pdf  -f b1.pdf --filter "Birth Rate Bin=1.5-3%"

**Comment by michaelharms6010** [comment]
That's _much_ nicer syntax! Thanks for that and for your testing on the workbook filter issue. I can work with this and wrap up my work with this much. Really appreciate the help.

**Comment by mkosmicki** [comment]
I'm liking the new syntax as well. I'm hopeful that I'll be able to export
my single view now. I won't be able to test until next week though.

Thanks for all your work on this.

-Michelle

**Comment by jacalata** [comment]
closing this as it sounds like we've confirmed that exporting a view and filtering with spaces in the parameter name works :) 
I opened a separate bug linked above to track filtering a workbook for export.
